name: M0-SessionLogger
main: me.M0dii.SessionLogger.Main
description: M0-SessionLogger
version: 1.3
api-version: 1.16
author: M0dii
permissions:
  m0sessionlogger.log:
    description: Log player sessions with this permission.